spring.application.name=your_details
spring.datasource.url=your_details
spring.datasource.username=your_details
spring.datasource.password=your_details

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

